// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: configuration_items.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConfigurationItem = `-- name: CreateConfigurationItem :one
INSERT INTO configuration_items (id, created_at, updated_at, name, organization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, organization_id
`

type CreateConfigurationItemParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	OrganizationID uuid.UUID
}

func (q *Queries) CreateConfigurationItem(ctx context.Context, arg CreateConfigurationItemParams) (ConfigurationItem, error) {
	row := q.db.QueryRowContext(ctx, createConfigurationItem,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.OrganizationID,
	)
	var i ConfigurationItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OrganizationID,
	)
	return i, err
}
