// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: incidents.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (id, created_at, updated_at, short_description, description, state, organization_id, configuration_item_id, company_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at, short_description, description, organization_id, configuration_item_id, company_id, state, assigned_to
`

type CreateIncidentParams struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ShortDescription    string
	Description         sql.NullString
	State               StateEnum
	OrganizationID      uuid.UUID
	ConfigurationItemID uuid.UUID
	CompanyID           uuid.UUID
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, createIncident,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ShortDescription,
		arg.Description,
		arg.State,
		arg.OrganizationID,
		arg.ConfigurationItemID,
		arg.CompanyID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortDescription,
		&i.Description,
		&i.OrganizationID,
		&i.ConfigurationItemID,
		&i.CompanyID,
		&i.State,
		&i.AssignedTo,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECt id, created_at, updated_at, short_description, description, organization_id, configuration_item_id, company_id, state, assigned_to FROM incidents WHERE id = $1
`

func (q *Queries) GetIncidentByID(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortDescription,
		&i.Description,
		&i.OrganizationID,
		&i.ConfigurationItemID,
		&i.CompanyID,
		&i.State,
		&i.AssignedTo,
	)
	return i, err
}

const getIncidentsByOrganizationID = `-- name: GetIncidentsByOrganizationID :many
SELECT incidents.id, incidents.created_at, incidents.updated_at, short_description, description, organization_id, configuration_item_id, company_id, state, assigned_to, users.id, users.created_at, users.updated_at, name, apikey, email, password FROM incidents
LEFT JOIN users
ON incidents.assigned_to = users.id
WHERE organization_id = $1
`

type GetIncidentsByOrganizationIDRow struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ShortDescription    string
	Description         sql.NullString
	OrganizationID      uuid.UUID
	ConfigurationItemID uuid.UUID
	CompanyID           uuid.UUID
	State               StateEnum
	AssignedTo          uuid.NullUUID
	ID_2                uuid.NullUUID
	CreatedAt_2         sql.NullTime
	UpdatedAt_2         sql.NullTime
	Name                sql.NullString
	Apikey              sql.NullString
	Email               sql.NullString
	Password            sql.NullString
}

func (q *Queries) GetIncidentsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]GetIncidentsByOrganizationIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncidentsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncidentsByOrganizationIDRow
	for rows.Next() {
		var i GetIncidentsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortDescription,
			&i.Description,
			&i.OrganizationID,
			&i.ConfigurationItemID,
			&i.CompanyID,
			&i.State,
			&i.AssignedTo,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name,
			&i.Apikey,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
