// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type StateEnum string

const (
	StateEnumNew        StateEnum = "New"
	StateEnumInProgress StateEnum = "In Progress"
	StateEnumAssigned   StateEnum = "Assigned"
	StateEnumOnHold     StateEnum = "On Hold"
	StateEnumResolved   StateEnum = "Resolved"
)

func (e *StateEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StateEnum(s)
	case string:
		*e = StateEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StateEnum: %T", src)
	}
	return nil
}

type NullStateEnum struct {
	StateEnum StateEnum
	Valid     bool // Valid is true if StateEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStateEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StateEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StateEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStateEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StateEnum), nil
}

type Account struct {
	ID                uuid.UUID
	UserId            uuid.UUID
	Type              string
	Provider          string
	ProviderAccountId string
	RefreshToken      sql.NullString
	AccessToken       sql.NullString
	ExpiresAt         sql.NullInt64
	IDToken           sql.NullString
	Scope             sql.NullString
	SessionState      sql.NullString
	TokenType         sql.NullString
}

type Company struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type ConfigurationItem struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Incident struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ShortDescription    string
	Description         sql.NullString
	ConfigurationItemID uuid.UUID
	CompanyID           uuid.UUID
	State               StateEnum
	AssignedTo          uuid.NullUUID
}

type Permission struct {
	ID        uuid.UUID
	Code      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Session struct {
	ID           uuid.UUID
	UserId       uuid.UUID
	Expires      time.Time
	SessionToken string
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FirstName     sql.NullString
	LastName      sql.NullString
	Email         string
	EmailVerified sql.NullTime
	Name          sql.NullString
	Image         sql.NullString
	Role          string
}

type UsersPermission struct {
	UserID       uuid.UUID
	PermissionID uuid.UUID
}

type VerificationToken struct {
	Identifier string
	Expires    time.Time
	Token      string
}
