// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	OrganizationID uuid.UUID
}

type ConfigurationItem struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	OrganizationID uuid.UUID
	CompanyID      uuid.UUID
}

type Incident struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ShortDescription    string
	Description         sql.NullString
	OrganizationID      uuid.UUID
	ConfigurationItemID uuid.UUID
	CompanyID           uuid.UUID
}

type Organization struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Name              string
	UserID            uuid.UUID
	IncidentsSequence int64
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Apikey    string
}
