# fly.toml app configuration file generated for frontend-patient-voice-578 on 2024-10-15T17:02:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-patient-voice-578'
primary_region = 'den'

[build]

[env]

BACKEND = "https://app-weathered-shadow-227.fly.dev/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
