root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./ticket-tracker"
  # cmd = "templ generate && tailwindcss -i input.css -o internal/server/static/css/tailwind.css && go build ."
  # remove tailwind for a bit it's messing with the frontend
  cmd = "templ generate && go build ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "frontend"]
  exclude_file = []
  exclude_regex = [".*_templ.go", "_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
