on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build production
        run: make build/prod/ticket-tracker

      - name: Migrate database
        run: ./migrateup.sh

      - name: Google Cloud Build
        run: gcloud builds submit --tag us-south1-docker.pkg.dev/ticket-tracker-438815/ticket-tracker-ar-repo/ticket-tracker:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy ticket-tracker --image us-south1-docker.pkg.dev/ticket-tracker-438815/ticket-tracker-ar-repo/ticket-tracker:latest --region us-central1 --allow-unauthenticated --project ticket-tracker-438815 --max-instances=4
